server:
  port: 9002

spring:
  datasource:
    url: jdbc:postgresql://<DB_HOST>:5432/data-servicedb
    username: <username>
    password: <password>
  jpa:
    hibernate:
      ddl-auto: none

eureka:
  client:
    service-url:
      defaultZone: http://<EUREKA_HOST>:8761/eureka
