apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:  # ✅ use stringData so you don’t have to base64 encode manually
  username: {{ .Values.db.username | quote }}
  password: {{ .Values.db.password | quote }}
